### ISSUE TITLE
First time using Plex Meta Manager and I'm getting an error

### ISSUE THREAD

**Issue by LimesKey** [mrbuckwheet/Plex-Meta-Manager-Config#1]
I installed Plex Meta Manager and moved all the files in this repo to my plex meta manager folder and then added all the API Keys. After setting `PMM_RUN` to `true` I get this error in my logs. I'm using unRAID. I'm assuming though this is another issue unrelated to your config files and I understand if you cannot help me.
```log
text  error  warn  system  array  login  

|       #mass_episode_audience_rating_update: mdb_tmdb     # Update audience ratings with tmdb for episodes not needed for tautulli |
|                                                                                                    |
| settings:                                                                                          |
|   cache: true                                                                                      |
|   cache_expiration: 60                                                                             |
|   asset_directory: config/assets                                                                   |
|   missing_path: config/missing                                                                     |
|   asset_folders: false                                                                             |
|   asset_depth: 0                                                                                   |
|   create_asset_folders: false                                                                      |
|   prioritize_assets: false                                                                         |
|   dimensional_asset_rename: false                                                                  |
|   download_url_assets: false                                                                       |
|   show_missing_season_assets: false                                                                |
|   show_missing_episode_assets: false                                                               |
|   show_asset_not_needed: false                                                                     |
|   sync_mode: sync                                                                                  |
|   minimum_items: 1                                                                                 |
|   default_collection_order:                                                                        |
|   delete_below_minimum: true                                                                       |
|   delete_not_scheduled: false                                                                      |
|   run_again_delay: 2                                                                               |
|   missing_only_released: false                                                                     |
|   only_filter_missing: false                                                                       |
|   show_unmanaged: true                                                                             |
|   show_filtered: false                                                                             |
|   show_options: false                                                                              |
|   show_missing: false                                                                              |
|   show_missing_assets: true                                                                        |
|   save_report: true                                                                                |
|   tvdb_language: eng                                                                               |
|   ignore_ids:                                                                                      |
|   ignore_imdb_ids:                                                                                 |
|   item_refresh_delay: 0                                                                            |
|   playlist_sync_to_user: all                                                                       |
|   playlist_exclude_user:                                                                           |
|   playlist_report: false                                                                           |
|   verify_ssl: true                                                                                 |
|   custom_repo:                                                                                     |
|   check_nightly: false                                                                             |
|   show_unconfigured: true                                                                          |
|   playlist_exclude_users:                                                                          |
| webhooks:                        # This is a webhook for notifiarr. if not needed you can add # infront of each line.  |
|   #error: (redacted)                                                                               |
|   #version: (redacted)                                                                             |
|   #run_start: (redacted)                                                                           |
|   #run_end: (redacted)                                                                             |
|   #changes: (redacted)                                                                             |
|   #delete: notifiarr                                                                               |
| plex:                            # Can be individually specified per library as well; REQUIRED for the script to run |
|   url: (redacted)                                                                                  |
|   token: (redacted)                                                                                |
|   timeout: 60                                                                                      |
|   clean_bundles: true                                                                              |
|   empty_trash: true                                                                                |
|   optimize: false                                                                                  |
| notifiarr:                                                                                         |
|   apikey: (redacted)                                                                               |
| tmdb:                            # REQUIRED for the script to run you need to create an account on tmdb.com |
|   apikey: (redacted)                                                                               |
|   language: en                                                                                     |
|   cache_expiration: 60                                                                             |
|   region:                                                                                          |
| mdblist:                         # REQUIRED for the script to run you need to create an account on mdblist.com, you can create an account with trakt and link it.  |
|   apikey: (redacted)                                                                               |
|   cache_expiration: 60                                                                             |
|                                                                                                    |
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 294, in start                                                |
|     config = ConfigFile(default_dir, attrs, secret_args)                                           |
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           |
|   File "/modules/config.py", line 252, in __init__                                                 |
|     if "changes" not in temp:                                                                      |
|        ^^^^^^^^^^^^^^^^^^^^^                                                                       |
| TypeError: argument of type 'NoneType' is not iterable                                             |
|                                                                                                    |
| argument of type 'NoneType' is not iterable                                                        |
|                                                                                                    |
|========================================= Critical Summary =========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     1 | argument of type 'NoneType' is not iterable                                                |
|                                                                                                    |
|====================================================================================================|
|                                            Finished Run                                            |
|                                          Version: 1.19.0                                           |
|                          Finished: 23:09:26 2023-04-16 Run Time: 0:00:00                           |
|====================================================================================================|
```
![image](https://user-images.githubusercontent.com/85136735/232369089-2538d4be-be0c-4dec-ba48-134631334290.png)

**Comment by mrbuckwheet** [comment]
Can you post the entire log file?

**Comment by LimesKey** [comment]
Yes!
[meta.log](https://github.com/mrbuckwheet/Plex-Meta-Manager-Config/files/11245928/meta.log)

**Comment by mrbuckwheet** [comment]
Are you using notifiarr? If not add a # in front of webhooks line and notifiarr and notifiarr apikey line. Is the entire github directory extracted into your config folder?

**Comment by LimesKey** [comment]
I am not using notifarr, I just commented out the lines now. Yes the entire github directory is extracted.

After commenting out the notifarr line, I seem to be getting a new error message. `Plex Error: Plex url is invalid` and `Config Error: No libraries were found in config`. The Plex URL should very much be valid, I entered `url: http://192.168.1.98:32400` for the Plex URL and then entered the API Key. The docker network type is set to my dockernet but I also tried setting it both to bridge and host mode.

Then for the `Config Error: No libraries were found in config` error, there should be libraries there, I see them myself and am very confused.

**Comment by mrbuckwheet** [comment]
Looks like the libraries in plex are not being matched. What names did you use in Plex for your TV and Movie libraries?

**Comment by mrbuckwheet** [comment]
Awesome. I would wait for the run to finish before opening an issue. Logs are key to diagnosing any issues you have. I will admit getting the initial setup is tough but if once configured properly around your system/setup the config.yml I made should run and work without issue.
